### PR TITLE
Build separate button css asset

### PR DESCRIPTION
**Pull request by namanaman**
- Set up separate Button CSS file that can be imported by a web component instead of the full NJWDS CSS styles

### CODE REVIEW

**Review by jasnoo — APPROVED** [review]
Just curious if there's any need for any USWDS styling around an icon to be included here in case the user wishes to use an icon button? Not sure if that's something that's purely handled by the NJWDS custom styling?

**Comment by namanaman** [comment]
@jasnoo Actually i'm glad you brought that up because I realize I've left out one of the core required packages that should also be forwarded with the button. Confused because icons had worked without, but maybe I was doing something wrong

**Comment by namanaman** [comment]
@jasnoo You were right good call! I had to add in `@forward "packages/usa-icon";` and `@forward "packages/usa-globals";`

**Comment by jasnoo** [comment]
Nice! yeah I noticed a min ago that there seemed to be something wonky with the styling as well with the icons, i know when I was styling the icon buttons that I had to play around to get those to stay in line (see how the icon leading looks taller). 

Screenshot 2024-11-18 at 5 18 13 PM


I see you just merged now so may or may not be a thing anymore, but yay for adding the packages!

**Pull request merged**
